import {
  phosphorArrowLeft,
  phosphorBriefcase,
  phosphorFloppyDisk,
  phosphorGoogleLogo,
  phosphorIdentificationCard,
  phosphorLock,
  phosphorMoon,
  phosphorPencilSimple,
  phosphorPlus,
  phosphorSignOut,
  phosphorSparkle,
  phosphorSun,
  phosphorTag,
  phosphorTrash,
  phosphorUserCircle,
} from '@ng-icons/phosphor-icons/regular';

export const APP_ICONS = {
  phosphorArrowLeft,
  phosphorBriefcase,
  phosphorFloppyDisk,
  phosphorGoogleLogo,
  phosphorIdentificationCard,
  phosphorLock,
  phosphorMoon,
  phosphorPencilSimple,
  phosphorPlus,
  phosphorSignOut,
  phosphorSparkle,
  phosphorSun,
  phosphorTag,
  phosphorTrash,
  phosphorUserCircle,
} as const;
