import {
  phosphorArrowClockwise,
  phosphorArrowLeft,
  phosphorChartBar,
  phosphorCheck,
  phosphorFunnel,
  phosphorMagnifyingGlass,
  phosphorMoon,
  phosphorPlus,
  phosphorPolygon,
  phosphorScales,
  phosphorSquaresFour,
  phosphorSun,
  phosphorTrash,
  phosphorWarningCircle,
  phosphorX,
} from '@ng-icons/phosphor-icons/regular';

export const APP_ICONS = {
  phosphorArrowClockwise,
  phosphorArrowLeft,
  phosphorChartBar,
  phosphorCheck,
  phosphorFunnel,
  phosphorMagnifyingGlass,
  phosphorMoon,
  phosphorPlus,
  phosphorPolygon,
  phosphorScales,
  phosphorSquaresFour,
  phosphorSun,
  phosphorTrash,
  phosphorWarningCircle,
  phosphorX,
} as const;
