import {
  phosphorArrowsDownUp,
  phosphorBasket,
  phosphorCloudArrowDown,
  phosphorCoins,
  phosphorFunnel,
  phosphorInfo,
  phosphorLeaf,
  phosphorListBullets,
  phosphorMoon,
  phosphorPlant,
  phosphorPlus,
  phosphorScales,
  phosphorSquaresFour,
  phosphorSun,
  phosphorTrash,
} from '@ng-icons/phosphor-icons/regular';

export const APP_ICONS = {
  phosphorArrowsDownUp,
  phosphorBasket,
  phosphorCloudArrowDown,
  phosphorCoins,
  phosphorFunnel,
  phosphorInfo,
  phosphorLeaf,
  phosphorListBullets,
  phosphorMoon,
  phosphorPlant,
  phosphorPlus,
  phosphorScales,
  phosphorSquaresFour,
  phosphorSun,
  phosphorTrash,
} as const;
