import {
  phosphorArrowsDownUp,
  phosphorBasket,
  phosphorCalendarBlank,
  phosphorCloudArrowDown,
  phosphorCoins,
  phosphorFunnel,
  phosphorInfo,
  phosphorLeaf,
  phosphorListBullets,
  phosphorMoon,
  phosphorPiggyBank,
  phosphorPlant,
  phosphorPlus,
  phosphorPottedPlant,
  phosphorReceipt,
  phosphorScales,
  phosphorSnowflake,
  phosphorSquaresFour,
  phosphorSun,
  phosphorTag,
  phosphorTrash,
  phosphorTrendDown,
  phosphorTrendUp,
} from '@ng-icons/phosphor-icons/regular';

export const APP_ICONS = {
  phosphorArrowsDownUp,
  phosphorBasket,
  phosphorCalendarBlank,
  phosphorCloudArrowDown,
  phosphorCoins,
  phosphorFunnel,
  phosphorInfo,
  phosphorLeaf,
  phosphorListBullets,
  phosphorMoon,
  phosphorPiggyBank,
  phosphorPlant,
  phosphorPlus,
  phosphorPottedPlant,
  phosphorReceipt,
  phosphorScales,
  phosphorSnowflake,
  phosphorSquaresFour,
  phosphorSun,
  phosphorTag,
  phosphorTrash,
  phosphorTrendDown,
  phosphorTrendUp,
} as const;
