import {
  SCENE_RAMP,
  type SceneColors,
  sceneRamp,
  SCENE_SEMANTIC,
  sceneSemantic,
  type SceneThemeTokens,
} from '@justin-croyable/design-system';

export const GARDEN_COLOR = {
  fieldSoil: 'fieldSoil',
  fieldFurrow: 'fieldFurrow',
  grass: 'grass',
  bedSoil: 'bedSoil',
  bedFurrow: 'bedFurrow',
  slot: 'slot',
  wood: 'wood',
  woodDark: 'woodDark',
  stone: 'stone',
  leafDeep: 'leafDeep',
  leaf: 'leaf',
  leafBright: 'leafBright',
  stem: 'stem',
  stemLight: 'stemLight',
  bark: 'bark',
  red: 'red',
  redDeep: 'redDeep',
  pink: 'pink',
  orange: 'orange',
  amber: 'amber',
  purple: 'purple',
  purpleDeep: 'purpleDeep',
  lime: 'lime',
  limeDeep: 'limeDeep',
  teal: 'teal',
  ivory: 'ivory',
  highlight: 'highlight',
  marker: 'marker',
} as const;

export type GardenColorName = (typeof GARDEN_COLOR)[keyof typeof GARDEN_COLOR];

export type GardenColors = SceneColors<GardenColorName>;

export const GARDEN_PALETTE: SceneThemeTokens<GardenColorName> = {
  light: {
    fieldSoil: sceneRamp(SCENE_RAMP.orange, 800, 1.05, 0.5),
    fieldFurrow: sceneRamp(SCENE_RAMP.orange, 900, 1.05, 0.45),
    grass: sceneRamp(SCENE_RAMP.primary, 700, 1.05, 0.42),
    bedSoil: sceneRamp(SCENE_RAMP.orange, 700, 1, 0.45),
    bedFurrow: sceneRamp(SCENE_RAMP.orange, 700, 1.14, 0.42),
    slot: sceneRamp(SCENE_RAMP.orange, 800, 1.14, 0.45),
    wood: sceneRamp(SCENE_RAMP.orange, 600, 1.05, 0.55),
    woodDark: sceneRamp(SCENE_RAMP.orange, 800, 1, 0.5),
    stone: sceneRamp(SCENE_RAMP.gray, 400),
    leafDeep: sceneRamp(SCENE_RAMP.primary, 800, 1.05, 0.9),
    leaf: sceneRamp(SCENE_RAMP.primary, 600),
    leafBright: sceneRamp(SCENE_RAMP.primary, 400),
    stem: sceneRamp(SCENE_RAMP.lime, 700),
    stemLight: sceneRamp(SCENE_RAMP.lime, 500),
    bark: sceneRamp(SCENE_RAMP.orange, 900, 1.15, 0.3),
    red: sceneSemantic(SCENE_SEMANTIC.error, 1.15),
    redDeep: sceneSemantic(SCENE_SEMANTIC.error),
    pink: sceneRamp(SCENE_RAMP.rose, 300),
    orange: sceneRamp(SCENE_RAMP.orange, 500),
    amber: sceneRamp(SCENE_RAMP.orange, 400),
    purple: sceneRamp(SCENE_RAMP.violet, 600),
    purpleDeep: sceneRamp(SCENE_RAMP.violet, 700),
    lime: sceneRamp(SCENE_RAMP.lime, 400),
    limeDeep: sceneRamp(SCENE_RAMP.lime, 600),
    teal: sceneRamp(SCENE_RAMP.cyan, 500),
    ivory: sceneRamp(SCENE_RAMP.gray, 100),
    highlight: sceneRamp(SCENE_RAMP.primary, 400),
    marker: sceneRamp(SCENE_RAMP.primary, 600),
  },
  dark: {
    fieldSoil: sceneRamp(SCENE_RAMP.orange, 800, 1, 0.5),
    fieldFurrow: sceneRamp(SCENE_RAMP.orange, 900, 0.85, 0.45),
    grass: sceneRamp(SCENE_RAMP.primary, 800, 0.95, 0.5),
    bedSoil: sceneRamp(SCENE_RAMP.orange, 700, 1, 0.45),
    bedFurrow: sceneRamp(SCENE_RAMP.orange, 700, 1.06, 0.42),
    slot: sceneRamp(SCENE_RAMP.orange, 800, 1.12, 0.45),
    wood: sceneRamp(SCENE_RAMP.orange, 700, 0.95, 0.55),
    woodDark: sceneRamp(SCENE_RAMP.orange, 900, 0.95, 0.5),
    stone: sceneRamp(SCENE_RAMP.gray, 600),
    leafDeep: sceneRamp(SCENE_RAMP.primary, 700, 1, 0.9),
    leaf: sceneRamp(SCENE_RAMP.primary, 500),
    leafBright: sceneRamp(SCENE_RAMP.primary, 300),
    stem: sceneRamp(SCENE_RAMP.lime, 600),
    stemLight: sceneRamp(SCENE_RAMP.lime, 400),
    bark: sceneRamp(SCENE_RAMP.orange, 900, 1, 0.3),
    red: sceneSemantic(SCENE_SEMANTIC.error, 1.3),
    redDeep: sceneSemantic(SCENE_SEMANTIC.error, 1.15),
    pink: sceneRamp(SCENE_RAMP.rose, 300),
    orange: sceneRamp(SCENE_RAMP.orange, 400),
    amber: sceneRamp(SCENE_RAMP.orange, 300),
    purple: sceneRamp(SCENE_RAMP.violet, 500),
    purpleDeep: sceneRamp(SCENE_RAMP.violet, 600),
    lime: sceneRamp(SCENE_RAMP.lime, 300),
    limeDeep: sceneRamp(SCENE_RAMP.lime, 500),
    teal: sceneRamp(SCENE_RAMP.cyan, 400),
    ivory: sceneRamp(SCENE_RAMP.gray, 200),
    highlight: sceneRamp(SCENE_RAMP.primary, 300),
    marker: sceneRamp(SCENE_RAMP.primary, 400),
  },
};
