import { type CropId } from '../../../core/potager.model';

import { GARDEN_COLOR, type GardenColorName } from './garden-palette';

export const PLANT_ARCHETYPE = {
  stakedVine: 'stakedVine',
  bush: 'bush',
  sprawler: 'sprawler',
  rosette: 'rosette',
  root: 'root',
  trellis: 'trellis',
  tree: 'tree',
  stalk: 'stalk',
} as const;

export type PlantArchetype = (typeof PLANT_ARCHETYPE)[keyof typeof PLANT_ARCHETYPE];

export const ROOT_SHAPE = {
  taproot: 'taproot',
  bulb: 'bulb',
  tuber: 'tuber',
  shaft: 'shaft',
} as const;

export type RootShape = (typeof ROOT_SHAPE)[keyof typeof ROOT_SHAPE];

export const FRUIT_SHAPE = {
  berry: 'berry',
  pod: 'pod',
  marrow: 'marrow',
  bunch: 'bunch',
  gourd: 'gourd',
} as const;

export type FruitShape = (typeof FRUIT_SHAPE)[keyof typeof FRUIT_SHAPE];

export type PlantModel = {
  readonly archetype: PlantArchetype;
  readonly height: number;
  readonly spread: number;
  readonly foliage: GardenColorName;
  readonly foliageAccent: GardenColorName;
  readonly stem: GardenColorName;
  readonly fruit: GardenColorName;
  readonly fruitCount: number;
  readonly fruitRadius: number;
  readonly fruitShape: FruitShape;
  readonly rootShape: RootShape;
  readonly spots: number;
  readonly sway: number;
};

const DEFAULT_MODEL: PlantModel = {
  archetype: PLANT_ARCHETYPE.bush,
  height: 0.6,
  spread: 0.4,
  foliage: GARDEN_COLOR.leaf,
  foliageAccent: GARDEN_COLOR.leafBright,
  stem: GARDEN_COLOR.stem,
  fruit: GARDEN_COLOR.red,
  fruitCount: 4,
  fruitRadius: 0.06,
  fruitShape: FRUIT_SHAPE.berry,
  rootShape: ROOT_SHAPE.taproot,
  spots: 6,
  sway: 0.035,
};

function plantModel(overrides: Partial<PlantModel>): PlantModel {
  return { ...DEFAULT_MODEL, ...overrides };
}

export const PLANT_MODEL_BY_CROP: Readonly<Record<CropId, PlantModel>> = {
  tomate: plantModel({
    archetype: PLANT_ARCHETYPE.stakedVine,
    height: 1.15,
    spread: 0.42,
    fruit: GARDEN_COLOR.red,
    fruitCount: 7,
    fruitRadius: 0.075,
    spots: 4,
    sway: 0.03,
  }),
  courgette: plantModel({
    archetype: PLANT_ARCHETYPE.sprawler,
    height: 0.52,
    spread: 0.62,
    foliage: GARDEN_COLOR.leafDeep,
    foliageAccent: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.limeDeep,
    fruitCount: 3,
    fruitRadius: 0.095,
    fruitShape: FRUIT_SHAPE.marrow,
    spots: 2,
    sway: 0.02,
  }),
  carotte: plantModel({
    archetype: PLANT_ARCHETYPE.root,
    height: 0.52,
    spread: 0.24,
    foliage: GARDEN_COLOR.leafBright,
    fruit: GARDEN_COLOR.orange,
    fruitRadius: 0.07,
    rootShape: ROOT_SHAPE.taproot,
    spots: 6,
    sway: 0.05,
  }),
  'pomme-de-terre': plantModel({
    archetype: PLANT_ARCHETYPE.root,
    height: 0.56,
    spread: 0.38,
    foliage: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.amber,
    fruitCount: 3,
    fruitRadius: 0.06,
    rootShape: ROOT_SHAPE.tuber,
    spots: 6,
    sway: 0.04,
  }),
  salade: plantModel({
    archetype: PLANT_ARCHETYPE.rosette,
    height: 0.36,
    spread: 0.38,
    foliage: GARDEN_COLOR.limeDeep,
    foliageAccent: GARDEN_COLOR.lime,
    fruitCount: 0,
    spots: 6,
    sway: 0.02,
  }),
  'haricot-vert': plantModel({
    archetype: PLANT_ARCHETYPE.trellis,
    height: 1.05,
    spread: 0.3,
    foliage: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.lime,
    fruitCount: 9,
    fruitRadius: 0.035,
    fruitShape: FRUIT_SHAPE.pod,
    spots: 4,
    sway: 0.025,
  }),
  poivron: plantModel({
    archetype: PLANT_ARCHETYPE.bush,
    height: 0.68,
    spread: 0.4,
    fruit: GARDEN_COLOR.red,
    fruitCount: 4,
    fruitRadius: 0.075,
    spots: 6,
  }),
  aubergine: plantModel({
    archetype: PLANT_ARCHETYPE.bush,
    height: 0.74,
    spread: 0.42,
    foliage: GARDEN_COLOR.leafDeep,
    fruit: GARDEN_COLOR.purpleDeep,
    fruitCount: 3,
    fruitRadius: 0.085,
    fruitShape: FRUIT_SHAPE.pod,
    spots: 4,
  }),
  concombre: plantModel({
    archetype: PLANT_ARCHETYPE.sprawler,
    height: 0.46,
    spread: 0.55,
    foliage: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.limeDeep,
    fruitCount: 3,
    fruitRadius: 0.07,
    fruitShape: FRUIT_SHAPE.marrow,
    spots: 3,
    sway: 0.02,
  }),
  radis: plantModel({
    archetype: PLANT_ARCHETYPE.root,
    height: 0.34,
    spread: 0.22,
    foliage: GARDEN_COLOR.leafBright,
    fruit: GARDEN_COLOR.pink,
    fruitRadius: 0.07,
    rootShape: ROOT_SHAPE.bulb,
    spots: 6,
    sway: 0.05,
  }),
  oignon: plantModel({
    archetype: PLANT_ARCHETYPE.root,
    height: 0.5,
    spread: 0.24,
    foliage: GARDEN_COLOR.stemLight,
    fruit: GARDEN_COLOR.ivory,
    fruitRadius: 0.075,
    rootShape: ROOT_SHAPE.bulb,
    spots: 6,
    sway: 0.045,
  }),
  poireau: plantModel({
    archetype: PLANT_ARCHETYPE.root,
    height: 0.72,
    spread: 0.22,
    foliage: GARDEN_COLOR.leafDeep,
    fruit: GARDEN_COLOR.ivory,
    fruitRadius: 0.05,
    rootShape: ROOT_SHAPE.shaft,
    spots: 6,
    sway: 0.03,
  }),
  epinard: plantModel({
    archetype: PLANT_ARCHETYPE.rosette,
    height: 0.34,
    spread: 0.36,
    foliage: GARDEN_COLOR.leafDeep,
    foliageAccent: GARDEN_COLOR.leaf,
    fruitCount: 0,
    spots: 6,
    sway: 0.025,
  }),
  courge: plantModel({
    archetype: PLANT_ARCHETYPE.sprawler,
    height: 0.58,
    spread: 0.7,
    foliage: GARDEN_COLOR.leafDeep,
    foliageAccent: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.orange,
    fruitCount: 2,
    fruitRadius: 0.13,
    fruitShape: FRUIT_SHAPE.gourd,
    spots: 2,
    sway: 0.015,
  }),
  fraise: plantModel({
    archetype: PLANT_ARCHETYPE.bush,
    height: 0.32,
    spread: 0.3,
    foliage: GARDEN_COLOR.leafBright,
    fruit: GARDEN_COLOR.red,
    fruitCount: 5,
    fruitRadius: 0.045,
    spots: 6,
    sway: 0.03,
  }),
  framboise: plantModel({
    archetype: PLANT_ARCHETYPE.bush,
    height: 0.95,
    spread: 0.24,
    foliage: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.pink,
    fruitCount: 9,
    fruitRadius: 0.035,
    spots: 4,
    sway: 0.04,
  }),
  pomme: plantModel({
    archetype: PLANT_ARCHETYPE.tree,
    height: 1.5,
    spread: 0.72,
    foliage: GARDEN_COLOR.leaf,
    foliageAccent: GARDEN_COLOR.leafDeep,
    fruit: GARDEN_COLOR.red,
    fruitCount: 7,
    fruitRadius: 0.075,
    spots: 1,
    sway: 0.012,
  }),
  poire: plantModel({
    archetype: PLANT_ARCHETYPE.tree,
    height: 1.55,
    spread: 0.68,
    foliage: GARDEN_COLOR.leaf,
    foliageAccent: GARDEN_COLOR.leafDeep,
    fruit: GARDEN_COLOR.lime,
    fruitCount: 6,
    fruitRadius: 0.075,
    fruitShape: FRUIT_SHAPE.pod,
    spots: 1,
    sway: 0.012,
  }),
  prune: plantModel({
    archetype: PLANT_ARCHETYPE.tree,
    height: 1.45,
    spread: 0.7,
    foliage: GARDEN_COLOR.leafDeep,
    foliageAccent: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.purple,
    fruitCount: 9,
    fruitRadius: 0.055,
    spots: 1,
    sway: 0.014,
  }),
  cerise: plantModel({
    archetype: PLANT_ARCHETYPE.tree,
    height: 1.5,
    spread: 0.7,
    foliage: GARDEN_COLOR.leaf,
    foliageAccent: GARDEN_COLOR.leafBright,
    fruit: GARDEN_COLOR.redDeep,
    fruitCount: 11,
    fruitRadius: 0.04,
    spots: 1,
    sway: 0.014,
  }),
  abricot: plantModel({
    archetype: PLANT_ARCHETYPE.tree,
    height: 1.42,
    spread: 0.68,
    foliage: GARDEN_COLOR.leaf,
    foliageAccent: GARDEN_COLOR.leafDeep,
    fruit: GARDEN_COLOR.amber,
    fruitCount: 8,
    fruitRadius: 0.055,
    spots: 1,
    sway: 0.013,
  }),
  peche: plantModel({
    archetype: PLANT_ARCHETYPE.tree,
    height: 1.4,
    spread: 0.7,
    foliage: GARDEN_COLOR.leafBright,
    foliageAccent: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.pink,
    fruitCount: 8,
    fruitRadius: 0.06,
    spots: 1,
    sway: 0.013,
  }),
  raisin: plantModel({
    archetype: PLANT_ARCHETYPE.trellis,
    height: 1.2,
    spread: 0.42,
    foliage: GARDEN_COLOR.leafDeep,
    foliageAccent: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.purpleDeep,
    fruitCount: 4,
    fruitRadius: 0.055,
    fruitShape: FRUIT_SHAPE.bunch,
    spots: 3,
    sway: 0.018,
  }),
  rhubarbe: plantModel({
    archetype: PLANT_ARCHETYPE.stalk,
    height: 0.76,
    spread: 0.44,
    foliage: GARDEN_COLOR.leafDeep,
    foliageAccent: GARDEN_COLOR.leaf,
    fruit: GARDEN_COLOR.pink,
    fruitCount: 5,
    fruitRadius: 0.035,
    spots: 3,
    sway: 0.028,
  }),
};
