import { LANG, type Pokemon } from './pokemon.model';

export const POKEMONS: readonly Pokemon[] = [
  {
    id: 1,
    names: [
      { lang: LANG.fr, value: 'Bulbizarre' },
      { lang: LANG.en, value: 'Bulbasaur' },
      { lang: LANG.de, value: 'Bisasam' },
      { lang: LANG.ja, value: 'Fushigidane' },
    ],
    types: ['Plante', 'Poison'],
    stats: { hp: 45, attack: 49, defense: 49, specialAttack: 65, specialDefense: 65, speed: 45 },
  },
  {
    id: 3,
    names: [
      { lang: LANG.fr, value: 'Florizarre' },
      { lang: LANG.en, value: 'Venusaur' },
      { lang: LANG.de, value: 'Bisaflor' },
      { lang: LANG.ja, value: 'Fushigibana' },
    ],
    types: ['Plante', 'Poison'],
    stats: { hp: 80, attack: 82, defense: 83, specialAttack: 100, specialDefense: 100, speed: 80 },
  },
  {
    id: 4,
    names: [
      { lang: LANG.fr, value: 'Salamèche' },
      { lang: LANG.en, value: 'Charmander' },
      { lang: LANG.de, value: 'Glumanda' },
      { lang: LANG.ja, value: 'Hitokage' },
    ],
    types: ['Feu'],
    stats: { hp: 39, attack: 52, defense: 43, specialAttack: 60, specialDefense: 50, speed: 65 },
  },
  {
    id: 6,
    names: [
      { lang: LANG.fr, value: 'Dracaufeu' },
      { lang: LANG.en, value: 'Charizard' },
      { lang: LANG.de, value: 'Glurak' },
      { lang: LANG.ja, value: 'Lizardon' },
    ],
    types: ['Feu', 'Vol'],
    stats: { hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100 },
  },
  {
    id: 7,
    names: [
      { lang: LANG.fr, value: 'Carapuce' },
      { lang: LANG.en, value: 'Squirtle' },
      { lang: LANG.de, value: 'Schiggy' },
      { lang: LANG.ja, value: 'Zenigame' },
    ],
    types: ['Eau'],
    stats: { hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43 },
  },
  {
    id: 9,
    names: [
      { lang: LANG.fr, value: 'Tortank' },
      { lang: LANG.en, value: 'Blastoise' },
      { lang: LANG.de, value: 'Turtok' },
      { lang: LANG.ja, value: 'Kamex' },
    ],
    types: ['Eau'],
    stats: { hp: 79, attack: 83, defense: 100, specialAttack: 85, specialDefense: 105, speed: 78 },
  },
  {
    id: 16,
    names: [
      { lang: LANG.fr, value: 'Roucool' },
      { lang: LANG.en, value: 'Pidgey' },
      { lang: LANG.de, value: 'Taubsi' },
      { lang: LANG.ja, value: 'Poppo' },
    ],
    types: ['Normal', 'Vol'],
    stats: { hp: 40, attack: 45, defense: 40, specialAttack: 35, specialDefense: 35, speed: 56 },
  },
  {
    id: 19,
    names: [
      { lang: LANG.fr, value: 'Rattata' },
      { lang: LANG.en, value: 'Rattata' },
      { lang: LANG.de, value: 'Rattfratz' },
      { lang: LANG.ja, value: 'Koratta' },
    ],
    types: ['Normal'],
    stats: { hp: 30, attack: 56, defense: 35, specialAttack: 25, specialDefense: 35, speed: 72 },
  },
  {
    id: 25,
    names: [
      { lang: LANG.fr, value: 'Pikachu' },
      { lang: LANG.en, value: 'Pikachu' },
      { lang: LANG.de, value: 'Pikachu' },
      { lang: LANG.ja, value: 'Pikachu' },
    ],
    types: ['Électrik'],
    stats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 },
  },
  {
    id: 26,
    names: [
      { lang: LANG.fr, value: 'Raichu' },
      { lang: LANG.en, value: 'Raichu' },
      { lang: LANG.de, value: 'Raichu' },
      { lang: LANG.ja, value: 'Raichu' },
    ],
    types: ['Électrik'],
    stats: { hp: 60, attack: 90, defense: 55, specialAttack: 90, specialDefense: 80, speed: 110 },
  },
  {
    id: 39,
    names: [
      { lang: LANG.fr, value: 'Rondoudou' },
      { lang: LANG.en, value: 'Jigglypuff' },
      { lang: LANG.de, value: 'Pummeluff' },
      { lang: LANG.ja, value: 'Purin' },
    ],
    types: ['Normal', 'Fée'],
    stats: { hp: 115, attack: 45, defense: 20, specialAttack: 45, specialDefense: 25, speed: 20 },
  },
  {
    id: 52,
    names: [
      { lang: LANG.fr, value: 'Miaouss' },
      { lang: LANG.en, value: 'Meowth' },
      { lang: LANG.de, value: 'Mauzi' },
      { lang: LANG.ja, value: 'Nyarth' },
    ],
    types: ['Normal'],
    stats: { hp: 40, attack: 45, defense: 35, specialAttack: 40, specialDefense: 40, speed: 90 },
  },
  {
    id: 54,
    names: [
      { lang: LANG.fr, value: 'Psykokwak' },
      { lang: LANG.en, value: 'Psyduck' },
      { lang: LANG.de, value: 'Enton' },
      { lang: LANG.ja, value: 'Koduck' },
    ],
    types: ['Eau'],
    stats: { hp: 50, attack: 52, defense: 48, specialAttack: 65, specialDefense: 50, speed: 55 },
  },
  {
    id: 59,
    names: [
      { lang: LANG.fr, value: 'Arcanin' },
      { lang: LANG.en, value: 'Arcanine' },
      { lang: LANG.de, value: 'Arkani' },
      { lang: LANG.ja, value: 'Windie' },
    ],
    types: ['Feu'],
    stats: { hp: 90, attack: 110, defense: 80, specialAttack: 100, specialDefense: 80, speed: 95 },
  },
  {
    id: 63,
    names: [
      { lang: LANG.fr, value: 'Abra' },
      { lang: LANG.en, value: 'Abra' },
      { lang: LANG.de, value: 'Abra' },
      { lang: LANG.ja, value: 'Casey' },
    ],
    types: ['Psy'],
    stats: { hp: 25, attack: 20, defense: 15, specialAttack: 105, specialDefense: 55, speed: 90 },
  },
  {
    id: 65,
    names: [
      { lang: LANG.fr, value: 'Alakazam' },
      { lang: LANG.en, value: 'Alakazam' },
      { lang: LANG.de, value: 'Simsala' },
      { lang: LANG.ja, value: 'Foodin' },
    ],
    types: ['Psy'],
    stats: { hp: 55, attack: 50, defense: 45, specialAttack: 135, specialDefense: 95, speed: 120 },
  },
  {
    id: 68,
    names: [
      { lang: LANG.fr, value: 'Mackogneur' },
      { lang: LANG.en, value: 'Machamp' },
      { lang: LANG.de, value: 'Machomei' },
      { lang: LANG.ja, value: 'Kairiky' },
    ],
    types: ['Combat'],
    stats: { hp: 90, attack: 130, defense: 80, specialAttack: 65, specialDefense: 85, speed: 55 },
  },
  {
    id: 94,
    names: [
      { lang: LANG.fr, value: 'Ectoplasma' },
      { lang: LANG.en, value: 'Gengar' },
      { lang: LANG.de, value: 'Gengar' },
      { lang: LANG.ja, value: 'Gangar' },
    ],
    types: ['Spectre', 'Poison'],
    stats: { hp: 60, attack: 65, defense: 60, specialAttack: 130, specialDefense: 75, speed: 110 },
  },
  {
    id: 95,
    names: [
      { lang: LANG.fr, value: 'Onix' },
      { lang: LANG.en, value: 'Onix' },
      { lang: LANG.de, value: 'Onix' },
      { lang: LANG.ja, value: 'Iwark' },
    ],
    types: ['Roche', 'Sol'],
    stats: { hp: 35, attack: 45, defense: 160, specialAttack: 30, specialDefense: 45, speed: 70 },
  },
  {
    id: 129,
    names: [
      { lang: LANG.fr, value: 'Magicarpe' },
      { lang: LANG.en, value: 'Magikarp' },
      { lang: LANG.de, value: 'Karpador' },
      { lang: LANG.ja, value: 'Koiking' },
    ],
    types: ['Eau'],
    stats: { hp: 20, attack: 10, defense: 55, specialAttack: 15, specialDefense: 20, speed: 80 },
  },
  {
    id: 130,
    names: [
      { lang: LANG.fr, value: 'Léviator' },
      { lang: LANG.en, value: 'Gyarados' },
      { lang: LANG.de, value: 'Garados' },
      { lang: LANG.ja, value: 'Gyarados' },
    ],
    types: ['Eau', 'Vol'],
    stats: { hp: 95, attack: 125, defense: 79, specialAttack: 60, specialDefense: 100, speed: 81 },
  },
  {
    id: 131,
    names: [
      { lang: LANG.fr, value: 'Lokhlass' },
      { lang: LANG.en, value: 'Lapras' },
      { lang: LANG.de, value: 'Lapras' },
      { lang: LANG.ja, value: 'Laplace' },
    ],
    types: ['Eau', 'Glace'],
    stats: { hp: 130, attack: 85, defense: 80, specialAttack: 85, specialDefense: 95, speed: 60 },
  },
  {
    id: 132,
    names: [
      { lang: LANG.fr, value: 'Métamorph' },
      { lang: LANG.en, value: 'Ditto' },
      { lang: LANG.de, value: 'Ditto' },
      { lang: LANG.ja, value: 'Metamon' },
    ],
    types: ['Normal'],
    stats: { hp: 48, attack: 48, defense: 48, specialAttack: 48, specialDefense: 48, speed: 48 },
  },
  {
    id: 133,
    names: [
      { lang: LANG.fr, value: 'Évoli' },
      { lang: LANG.en, value: 'Eevee' },
      { lang: LANG.de, value: 'Evoli' },
      { lang: LANG.ja, value: 'Eievui' },
    ],
    types: ['Normal'],
    stats: { hp: 55, attack: 55, defense: 50, specialAttack: 45, specialDefense: 65, speed: 55 },
  },
  {
    id: 134,
    names: [
      { lang: LANG.fr, value: 'Aquali' },
      { lang: LANG.en, value: 'Vaporeon' },
      { lang: LANG.de, value: 'Aquana' },
      { lang: LANG.ja, value: 'Showers' },
    ],
    types: ['Eau'],
    stats: { hp: 130, attack: 65, defense: 60, specialAttack: 110, specialDefense: 95, speed: 65 },
  },
  {
    id: 135,
    names: [
      { lang: LANG.fr, value: 'Voltali' },
      { lang: LANG.en, value: 'Jolteon' },
      { lang: LANG.de, value: 'Blitza' },
      { lang: LANG.ja, value: 'Thunders' },
    ],
    types: ['Électrik'],
    stats: { hp: 65, attack: 65, defense: 60, specialAttack: 110, specialDefense: 95, speed: 130 },
  },
  {
    id: 136,
    names: [
      { lang: LANG.fr, value: 'Pyroli' },
      { lang: LANG.en, value: 'Flareon' },
      { lang: LANG.de, value: 'Flamara' },
      { lang: LANG.ja, value: 'Booster' },
    ],
    types: ['Feu'],
    stats: { hp: 65, attack: 130, defense: 60, specialAttack: 95, specialDefense: 110, speed: 65 },
  },
  {
    id: 143,
    names: [
      { lang: LANG.fr, value: 'Ronflex' },
      { lang: LANG.en, value: 'Snorlax' },
      { lang: LANG.de, value: 'Relaxo' },
      { lang: LANG.ja, value: 'Kabigon' },
    ],
    types: ['Normal'],
    stats: { hp: 160, attack: 110, defense: 65, specialAttack: 65, specialDefense: 110, speed: 30 },
  },
  {
    id: 149,
    names: [
      { lang: LANG.fr, value: 'Dracolosse' },
      { lang: LANG.en, value: 'Dragonite' },
      { lang: LANG.de, value: 'Dragoran' },
      { lang: LANG.ja, value: 'Kairyu' },
    ],
    types: ['Dragon', 'Vol'],
    stats: { hp: 91, attack: 134, defense: 95, specialAttack: 100, specialDefense: 100, speed: 80 },
  },
  {
    id: 150,
    names: [
      { lang: LANG.fr, value: 'Mewtwo' },
      { lang: LANG.en, value: 'Mewtwo' },
      { lang: LANG.de, value: 'Mewtu' },
      { lang: LANG.ja, value: 'Mewtwo' },
    ],
    types: ['Psy'],
    stats: { hp: 106, attack: 110, defense: 90, specialAttack: 154, specialDefense: 90, speed: 130 },
  },
  {
    id: 151,
    names: [
      { lang: LANG.fr, value: 'Mew' },
      { lang: LANG.en, value: 'Mew' },
      { lang: LANG.de, value: 'Mew' },
      { lang: LANG.ja, value: 'Mew' },
    ],
    types: ['Psy'],
    stats: { hp: 100, attack: 100, defense: 100, specialAttack: 100, specialDefense: 100, speed: 100 },
  },
  {
    id: 448,
    names: [
      { lang: LANG.fr, value: 'Lucario' },
      { lang: LANG.en, value: 'Lucario' },
      { lang: LANG.de, value: 'Lucario' },
      { lang: LANG.ja, value: 'Lucario' },
    ],
    types: ['Combat', 'Acier'],
    stats: { hp: 70, attack: 110, defense: 70, specialAttack: 115, specialDefense: 70, speed: 90 },
  },
];
