export * from './generic-skeleton.component';
export * from './list-skeleton.component';
export * from './detail-skeleton.component';
export * from './dashboard-skeleton.component';
export * from './map-skeleton.component';
export * from './form-skeleton.component';
export * from './grid-skeleton.component';
export * from './page-skeletons.imports';
export * from './default-route-skeletons';
